Attribute VB_Name = "modAIMConstant"
' OSERVICE (0x0001)
Public Const OSERVICE_USER_FLAG_DAMNED_TRANSIENT As Long = &H1
Public Const OSERVICE_USER_FLAG_ADMINISTRATOR As Long = &H2
Public Const OSERVICE_USER_FLAG_AOL As Long = &H4
Public Const OSERVICE_USER_FLAG_OSCAR_PAY As Long = &H8
Public Const OSERVICE_USER_FLAG_OSCAR_FREE As Long = &H10
Public Const OSERVICE_USER_FLAG_UNAVAILABLE As Long = &H20
Public Const OSERVICE_USER_FLAG_ICQ As Long = &H40
Public Const OSERVICE_USER_FLAG_WIRELESS As Long = &H80
Public Const OSERVICE_USER_FLAG_INTERNAL As Long = &H100
Public Const OSERVICE_USER_FLAG_FISH As Long = &H200
Public Const OSERVICE_USER_FLAG_BOT As Long = &H400
Public Const OSERVICE_USER_FLAG_BEAST As Long = &H800

' FEEDBAG (0x0013)
Public Const FEEDBAG_STATUS_CODES_SUCCESS As Long = &H0
Public Const FEEDBAG_STATUS_CODES_DB_ERROR As Long = &H1
Public Const FEEDBAG_STATUS_CODES_NOT_FOUND As Long = &H2
Public Const FEEDBAG_STATUS_CODES_ALREADY_EXISTS As Long = &H3
Public Const FEEDBAG_STATUS_CODES_UNAVAILABLE As Long = &H5
Public Const FEEDBAG_STATUS_CODES_BAD_REQUEST As Long = &HA
Public Const FEEDBAG_STATUS_CODES_DB_TIMEOUT As Long = &HB
Public Const FEEDBAG_STATUS_CODES_OVER_ROW_LIMIT As Long = &HC
Public Const FEEDBAG_STATUS_CODES_NOT_EXECUTED As Long = &HD
Public Const FEEDBAG_STATUS_CODES_AUTH_REQUIRED As Long = &HE
Public Const FEEDBAG_STATUS_CODES_AUTO_AUTH As Long = &HF
Public Const FEEDBAG_STATUS_CODES_BAD_LOGIN_ID As Long = &H10
Public Const FEEDBAG_STATUS_CODES_OVER_BUDDY_LIMIT As Long = &H11
Public Const FEEDBAG_STATUS_CODES_INSERT_SMART_GROUP As Long = &H14
Public Const FEEDBAG_STATUS_CODES_TIMEOUT As Long = &H1A
